// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO_lInvM-ADSgIzZgVD-lsf372Fbd0nAY',
    appId: '1:219817684780:web:977cc7003d9eeb07e88689',
    messagingSenderId: '219817684780',
    projectId: 'little-steps-tracker-1cac4',
    authDomain: 'little-steps-tracker-1cac4.firebaseapp.com',
    storageBucket: 'little-steps-tracker-1cac4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaLWpjjN6StfvnkkIZ_96xrpHhvWgPnGo',
    appId: '1:219817684780:android:e682a4821ecdbf46e88689',
    messagingSenderId: '219817684780',
    projectId: 'little-steps-tracker-1cac4',
    storageBucket: 'little-steps-tracker-1cac4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqIrDgtU8zofgdhplQEmP2Vvh84hEC9VU',
    appId: '1:219817684780:ios:f164b6c93a33a4ace88689',
    messagingSenderId: '219817684780',
    projectId: 'little-steps-tracker-1cac4',
    storageBucket: 'little-steps-tracker-1cac4.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqIrDgtU8zofgdhplQEmP2Vvh84hEC9VU',
    appId: '1:219817684780:ios:f164b6c93a33a4ace88689',
    messagingSenderId: '219817684780',
    projectId: 'little-steps-tracker-1cac4',
    storageBucket: 'little-steps-tracker-1cac4.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO_lInvM-ADSgIzZgVD-lsf372Fbd0nAY',
    appId: '1:219817684780:web:2ee2883df342e0a3e88689',
    messagingSenderId: '219817684780',
    projectId: 'little-steps-tracker-1cac4',
    authDomain: 'little-steps-tracker-1cac4.firebaseapp.com',
    storageBucket: 'little-steps-tracker-1cac4.firebasestorage.app',
  );
}
